apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-website
  namespace: ecommerce
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
      - name: ecommerce-container
        image: abhishek0083/my-website:latest
        ports:
        - containerPort: 80
